### ISSUE TITLE
Primitive Data types usage

### ISSUE THREAD

**Issue by gurmeherchawla** [leonardvandriel/Tosti#10]
When using [NSString stringWithFormat:] or NSLog(), the string returns an incorrect value for variables of primitive data types such as int, double, etc. Fo example, while printing '1' from the code, the result is '21', for '2' it's 37, etc.
Does Tosti not support it due to it being a C type, or is it a bug (Since the difference mostly seems to be of 16)?

**Comment by leonardvandriel** [comment]
Thanks for reporting that. I did was able to reproduce the bug, but will need to look in to this next week. 

The `NSLog` wrapper is defined in `TOCocoa.m`, in case you want to take a closer look. This code deals with a variable argument list, which might be misaligned. Things seem to go wrong in `- (id)evalInvoke:(NSArray *)statement index:(NSUInteger)index` in `TOEval.m` where argument `1` is evaluated to something else.

**Comment by leonardvandriel** [comment]
@gurmeherchawla, I had another look at it and realized that instead of `%i`, you should use `%@`. This is explained in the readme:

> Note the %@ in the NSLog format string: all entities in Tosti are objects.

In short: `1` is an `NSNumber` object, so when you use `%i`, it casts the object pointer to an `int`. This is all consequence of the fact that Tosti supports most Objective-C but no pure C.

**Comment by gurmeherchawla** [comment]
Got it. Thank You

**Comment by gurmeherchawla** [comment]
Does Tosti Support block variables, for instance, to be used in 'presentViewController:animated:completion'?

**Comment by leonardvandriel** [comment]
it does, just provide the block as `^{..}`. In the Touch demo app you can try this:

    vc = [[UIViewController alloc] init]
    dispatch_async(^{
        [self.delegate presentViewController:vc animated:true completion:^{
            NSLog("done")
        }]
    })

**Comment by gurmeherchawla** [comment]
What about assigning the block to a variable?

**Comment by leonardvandriel** [comment]
That should work too.

**Comment by gurmeherchawla** [comment]
It doesn't seem to be working. 
Could you please test out a snippet with declaration and definition of a block variable separately, and paste the same here?

**Comment by leonardvandriel** [comment]
try:

    vc = [[UIViewController alloc] init]
    block = ^{NSLog("done")}
    dispatch_async(^{
        [self.delegate presentViewController:vc animated:true completion:block]
    })

or if you like:

    vc = [[UIViewController alloc] init]
    block = ^{NSLog("done")}
    block2 = ^{[self.delegate presentViewController:vc animated:true completion:block]}
    dispatch_async(block2)
