### ISSUE TITLE
Interpretation of Classes

### ISSUE THREAD

**Issue by gurmeherchawla** [leonardvandriel/Tosti#9]
I have observed the Tosti interprets the code as a global scope.
How do I declare and define classes and methods I want to be interpreted?

**Comment by leonardvandriel** [comment]
Hi @gurmeherchawla, thanks for reaching out. Currently Tosti does not support code structures like Objective-C classes and methods. It wouldn't be too hard to extend the framework to do so, but I felt that would be a bit beyond the scope of the project.

The quickest solution would be to rewrite your methods to use block syntax and move all code out of the class. That's not super satisfying, but hope it helps.

Keep in mind that Tosti only supports a very limited subset of the C and Ojective-C syntax. The idea was mostly to just allow short and simple scripts to be run inside a deployed application.

**Comment by gurmeherchawla** [comment]
Thank You for your support.
